version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080

  # server:
  #   env_file: .env
  #   build: 
  #     context: ./server/
  #     dockerfile: ./server.dockerfile
  #   image: isuct/web-app:server
  #   environment:
  #     - SOME_VAR=my_var
  #   ports:
  #     - 4000:3000
  #   depends_on:
  #     - db

  # client:
  #   env_file: .env
  #   build: 
  #     context: ./client/
  #     dockerfile: ./client.dockerfile
  #   image: jskonst/web-app:client
  #   environment:
  #     - SOME_VAR=another_var
  #   ports:
  #     - 5000:3000
  #   depends_on:
  #     - server
volumes:
  pgdata:
    external: true