name: Docker Image CI

on: [ push,  pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: | 
        cd ./server
        docker build . --file server.dockerfile --tag jskonst/web-app:server
    - name: Docker push
      run: |
        docker push jskonst/web-app:server
